### ISSUE TITLE
Feature: Prometheus/OpenMetrics API endpoint

### ISSUE THREAD

**Issue by SuperQ** [DanielWinks/pwrstat_docker#8]
I'd like to use Prometheus to monitor pwerstat data. This would require adding a `/metrics` API endpoint via the [Prometheus python client](https://github.com/prometheus/client_python).

Is there any interest in adding this feature?

**Comment by DanielWinks** [comment]
I don't use Prometheus, so if you want to add it and provide a pull request, I would review/merge that in, but I won't be able to devote enough time to this to add it myself.

**Comment by SuperQ** [comment]
That's absolutely fine, I'm happy to do the work. I was just looking to see if it was something that would be accepted before spending the time on it. :smile:

**Comment by imle** [comment]
Did the work for this in #11.

**Comment by DanielWinks** [comment]
Looks good. Merged.

**Comment by jr0dd** [comment]
> Did the work for this in #11.

Just curious if you had any rules configured for alertmanager. I'm definitely a Prometheus noob here.
